import React from "react";
import { TextInput as RNTextInput, TextInputProps as RNTextInputProps, TextStyle, ViewStyle } from "react-native";
export type InputSize = "sm" | "md" | "lg";
export type InputVariant = "default" | "glass" | "filled" | "bordered";
export type InputProps = Omit<RNTextInputProps, "size"> & {
    size?: InputSize;
    variant?: InputVariant;
    label?: string;
    helperText?: string;
    error?: string;
    success?: boolean;
    required?: boolean;
    disabled?: boolean;
    clearable?: boolean;
    onClear?: () => void;
    leftIcon?: React.ReactNode;
    rightIcon?: React.ReactNode;
    prefix?: string;
    suffix?: string;
    loading?: boolean;
    containerStyle?: ViewStyle;
    inputStyle?: TextStyle;
};
export declare const Input: React.ForwardRefExoticComponent<Omit<RNTextInputProps, "size"> & {
    size?: InputSize;
    variant?: InputVariant;
    label?: string;
    helperText?: string;
    error?: string;
    success?: boolean;
    required?: boolean;
    disabled?: boolean;
    clearable?: boolean;
    onClear?: () => void;
    leftIcon?: React.ReactNode;
    rightIcon?: React.ReactNode;
    prefix?: string;
    suffix?: string;
    loading?: boolean;
    containerStyle?: ViewStyle;
    inputStyle?: TextStyle;
} & React.RefAttributes<RNTextInput>>;
export declare const TextInput: React.ForwardRefExoticComponent<Omit<RNTextInputProps, "size"> & {
    size?: InputSize;
    variant?: InputVariant;
    label?: string;
    helperText?: string;
    error?: string;
    success?: boolean;
    required?: boolean;
    disabled?: boolean;
    clearable?: boolean;
    onClear?: () => void;
    leftIcon?: React.ReactNode;
    rightIcon?: React.ReactNode;
    prefix?: string;
    suffix?: string;
    loading?: boolean;
    containerStyle?: ViewStyle;
    inputStyle?: TextStyle;
} & React.RefAttributes<RNTextInput>>;
//# sourceMappingURL=Input.d.ts.map