import React from "react";
import { IconProps } from "./types";
export * from "./SvgIcon";
export * from "./types";
export * from "./icons";
export type IconName = "chevron-right" | "chevron-left" | "chevron-up" | "chevron-down" | "chevrons-right" | "chevrons-left" | "chevrons-up" | "chevrons-down" | "arrow-right" | "arrow-left" | "arrow-up" | "arrow-down" | "arrow-up-right" | "arrow-up-left" | "arrow-down-right" | "arrow-down-left" | "corner-down-right" | "corner-down-left" | "corner-up-right" | "corner-up-left" | "menu" | "close" | "x" | "x-circle" | "plus" | "plus-circle" | "minus" | "minus-circle" | "check" | "check-check" | "check-circle" | "check-square" | "home" | "compass" | "map" | "map-pin" | "navigation" | "navigation-2" | "layers" | "layout" | "grid" | "sidebar" | "columns" | "rows" | "maximize" | "maximize-2" | "minimize" | "minimize-2" | "sliders" | "filter" | "search" | "zoom-in" | "zoom-out" | "external-link" | "link" | "unlink" | "more-horizontal" | "more-vertical" | "toggle-left" | "toggle-right" | "edit" | "edit-2" | "edit-3" | "pen" | "pencil" | "trash" | "trash-2" | "copy" | "clipboard" | "scissors" | "crop" | "rotate-ccw" | "rotate-cw" | "undo" | "redo" | "refresh" | "refresh-cw" | "refresh-ccw" | "sync" | "download" | "upload" | "download-cloud" | "upload-cloud" | "pin" | "bookmark" | "tag" | "send" | "share" | "share-2" | "flag" | "settings" | "tool" | "wrench" | "save" | "palette" | "sparkles" | "monitor" | "laptop" | "smartphone" | "tablet" | "watch" | "tv" | "hard-drive" | "cpu" | "server" | "database" | "wifi" | "wifi-off" | "bluetooth" | "battery" | "battery-charging" | "power" | "cast" | "printer" | "qr-code" | "barcode" | "user" | "user-plus" | "user-minus" | "user-check" | "user-x" | "users" | "message-square" | "message-circle" | "mail" | "inbox" | "phone" | "phone-call" | "phone-off" | "bell" | "bell-off" | "at-sign" | "globe" | "rss" | "lock" | "unlock" | "key" | "shield" | "shield-check" | "shield-alert" | "shield-off" | "eye" | "eye-off" | "alert-circle" | "alert-triangle" | "help-circle" | "info" | "play" | "play-circle" | "pause" | "pause-circle" | "stop" | "stop-circle" | "fast-forward" | "rewind" | "volume" | "volume-1" | "volume-2" | "volume-x" | "mic" | "mic-off" | "camera" | "video" | "video-off" | "image" | "music" | "headphones" | "film" | "dollar" | "dollar-sign" | "credit-card" | "wallet" | "receipt" | "shopping-cart" | "shopping-bag" | "percent" | "gift" | "trophy" | "award" | "target" | "trending-up" | "trending-down" | "activity" | "bar-chart" | "bar-chart-2" | "pie-chart" | "code" | "command" | "terminal" | "git-branch" | "git-commit" | "git-merge" | "git-pull-request" | "box" | "package" | "braces" | "file" | "file-code" | "file-text" | "file-plus" | "file-minus" | "file-check" | "book" | "book-open" | "folder" | "folder-plus" | "folder-minus" | "clock" | "calendar" | "sun" | "moon" | "cloud" | "cloud-rain" | "cloud-lightning" | "cloud-snow" | "zap" | "flame" | "droplet" | "wind" | "star" | "heart" | "thumbs-up" | "thumbs-down" | "coffee" | "rocket" | "lightbulb" | "anchor";
export declare const iconMap: Record<IconName, React.FC<IconProps>>;
export type DynamicIconProps = IconProps & {
    name: IconName;
};
/**
 * Dynamic Universal Icon component:
 * `<Icon name="sparkles" size={24} color={semanticColors.primary} />`
 */
export declare const Icon: React.FC<DynamicIconProps>;
//# sourceMappingURL=index.d.ts.map