import React from "react";
import { View, ViewStyle } from "react-native";
import { Spacing } from "@unconfused-ui/tokens";
import { BoxProps } from "./Box";
export type StackDirection = "vertical" | "horizontal" | "row" | "column" | "row-reverse" | "column-reverse";
export type StackProps = BoxProps & {
    direction?: StackDirection;
    gap?: keyof Spacing | number;
    align?: ViewStyle["alignItems"];
    justify?: ViewStyle["justifyContent"];
    wrap?: boolean | ViewStyle["flexWrap"];
    reverse?: boolean;
    divider?: React.ReactElement;
    staggerDelay?: number;
    children?: React.ReactNode;
};
export declare const Stack: React.ForwardRefExoticComponent<import("react-native").ViewProps & {
    padding?: keyof Spacing | number;
    p?: keyof Spacing | number;
    paddingHorizontal?: keyof Spacing | number;
    px?: keyof Spacing | number;
    paddingVertical?: keyof Spacing | number;
    py?: keyof Spacing | number;
    paddingTop?: keyof Spacing | number;
    pt?: keyof Spacing | number;
    paddingBottom?: keyof Spacing | number;
    pb?: keyof Spacing | number;
    paddingLeft?: keyof Spacing | number;
    pl?: keyof Spacing | number;
    paddingRight?: keyof Spacing | number;
    pr?: keyof Spacing | number;
    margin?: keyof Spacing | number;
    m?: keyof Spacing | number;
    marginHorizontal?: keyof Spacing | number;
    mx?: keyof Spacing | number;
    marginVertical?: keyof Spacing | number;
    my?: keyof Spacing | number;
    marginTop?: keyof Spacing | number;
    mt?: keyof Spacing | number;
    marginBottom?: keyof Spacing | number;
    mb?: keyof Spacing | number;
    marginLeft?: keyof Spacing | number;
    ml?: keyof Spacing | number;
    marginRight?: keyof Spacing | number;
    mr?: keyof Spacing | number;
    width?: ViewStyle["width"];
    w?: ViewStyle["width"];
    height?: ViewStyle["height"];
    h?: ViewStyle["height"];
    minWidth?: ViewStyle["minWidth"];
    minW?: ViewStyle["minWidth"];
    maxWidth?: ViewStyle["maxWidth"];
    maxW?: ViewStyle["maxWidth"];
    minHeight?: ViewStyle["minHeight"];
    minH?: ViewStyle["minHeight"];
    maxHeight?: ViewStyle["maxHeight"];
    maxH?: ViewStyle["maxHeight"];
    flex?: ViewStyle["flex"];
    flexGrow?: ViewStyle["flexGrow"];
    flexShrink?: ViewStyle["flexShrink"];
    flexBasis?: ViewStyle["flexBasis"];
    direction?: ViewStyle["flexDirection"];
    flexDirection?: ViewStyle["flexDirection"];
    align?: ViewStyle["alignItems"];
    alignItems?: ViewStyle["alignItems"];
    justify?: ViewStyle["justifyContent"];
    justifyContent?: ViewStyle["justifyContent"];
    alignSelf?: ViewStyle["alignSelf"];
    wrap?: boolean | ViewStyle["flexWrap"];
    flexWrap?: ViewStyle["flexWrap"];
    gap?: keyof Spacing | number;
    bg?: string;
    backgroundColor?: string;
    radius?: keyof import("@unconfused-ui/tokens").Radii | number;
    rounded?: keyof import("@unconfused-ui/tokens").Radii | number;
    borderWidth?: number;
    borderColor?: string;
    borderStyle?: ViewStyle["borderStyle"];
    shadow?: keyof import("@unconfused-ui/tokens").Shadows;
    overflow?: ViewStyle["overflow"];
    opacity?: number;
    variant?: import("./Box").BoxVariant;
    children?: React.ReactNode;
} & {
    direction?: StackDirection;
    gap?: keyof Spacing | number;
    align?: ViewStyle["alignItems"];
    justify?: ViewStyle["justifyContent"];
    wrap?: boolean | ViewStyle["flexWrap"];
    reverse?: boolean;
    divider?: React.ReactElement;
    staggerDelay?: number;
    children?: React.ReactNode;
} & React.RefAttributes<View>>;
//# sourceMappingURL=Stack.d.ts.map