import React from "react";
import { View as RNView, ViewProps as RNViewProps, ViewStyle } from "react-native";
import { BoxProps } from "./Box";
export type ViewProps = BoxProps;
export declare const View: React.ForwardRefExoticComponent<RNViewProps & {
    padding?: keyof import("@unconfused-ui/tokens").Spacing | number;
    p?: keyof import("@unconfused-ui/tokens").Spacing | number;
    paddingHorizontal?: keyof import("@unconfused-ui/tokens").Spacing | number;
    px?: keyof import("@unconfused-ui/tokens").Spacing | number;
    paddingVertical?: keyof import("@unconfused-ui/tokens").Spacing | number;
    py?: keyof import("@unconfused-ui/tokens").Spacing | number;
    paddingTop?: keyof import("@unconfused-ui/tokens").Spacing | number;
    pt?: keyof import("@unconfused-ui/tokens").Spacing | number;
    paddingBottom?: keyof import("@unconfused-ui/tokens").Spacing | number;
    pb?: keyof import("@unconfused-ui/tokens").Spacing | number;
    paddingLeft?: keyof import("@unconfused-ui/tokens").Spacing | number;
    pl?: keyof import("@unconfused-ui/tokens").Spacing | number;
    paddingRight?: keyof import("@unconfused-ui/tokens").Spacing | number;
    pr?: keyof import("@unconfused-ui/tokens").Spacing | number;
    margin?: keyof import("@unconfused-ui/tokens").Spacing | number;
    m?: keyof import("@unconfused-ui/tokens").Spacing | number;
    marginHorizontal?: keyof import("@unconfused-ui/tokens").Spacing | number;
    mx?: keyof import("@unconfused-ui/tokens").Spacing | number;
    marginVertical?: keyof import("@unconfused-ui/tokens").Spacing | number;
    my?: keyof import("@unconfused-ui/tokens").Spacing | number;
    marginTop?: keyof import("@unconfused-ui/tokens").Spacing | number;
    mt?: keyof import("@unconfused-ui/tokens").Spacing | number;
    marginBottom?: keyof import("@unconfused-ui/tokens").Spacing | number;
    mb?: keyof import("@unconfused-ui/tokens").Spacing | number;
    marginLeft?: keyof import("@unconfused-ui/tokens").Spacing | number;
    ml?: keyof import("@unconfused-ui/tokens").Spacing | number;
    marginRight?: keyof import("@unconfused-ui/tokens").Spacing | number;
    mr?: keyof import("@unconfused-ui/tokens").Spacing | number;
    width?: ViewStyle["width"];
    w?: ViewStyle["width"];
    height?: ViewStyle["height"];
    h?: ViewStyle["height"];
    minWidth?: ViewStyle["minWidth"];
    minW?: ViewStyle["minWidth"];
    maxWidth?: ViewStyle["maxWidth"];
    maxW?: ViewStyle["maxWidth"];
    minHeight?: ViewStyle["minHeight"];
    minH?: ViewStyle["minHeight"];
    maxHeight?: ViewStyle["maxHeight"];
    maxH?: ViewStyle["maxHeight"];
    flex?: ViewStyle["flex"];
    flexGrow?: ViewStyle["flexGrow"];
    flexShrink?: ViewStyle["flexShrink"];
    flexBasis?: ViewStyle["flexBasis"];
    direction?: ViewStyle["flexDirection"];
    flexDirection?: ViewStyle["flexDirection"];
    align?: ViewStyle["alignItems"];
    alignItems?: ViewStyle["alignItems"];
    justify?: ViewStyle["justifyContent"];
    justifyContent?: ViewStyle["justifyContent"];
    alignSelf?: ViewStyle["alignSelf"];
    wrap?: boolean | ViewStyle["flexWrap"];
    flexWrap?: ViewStyle["flexWrap"];
    gap?: keyof import("@unconfused-ui/tokens").Spacing | number;
    bg?: string;
    backgroundColor?: string;
    radius?: keyof import("@unconfused-ui/tokens").Radii | number;
    rounded?: keyof import("@unconfused-ui/tokens").Radii | number;
    borderWidth?: number;
    borderColor?: string;
    borderStyle?: ViewStyle["borderStyle"];
    shadow?: keyof import("@unconfused-ui/tokens").Shadows;
    overflow?: ViewStyle["overflow"];
    opacity?: number;
    variant?: import("./Box").BoxVariant;
    children?: React.ReactNode;
} & React.RefAttributes<RNView>>;
//# sourceMappingURL=View.d.ts.map